const express = require('express')
const { viewCamps, viewCamp, addCamp, deleteCamp, updateCamp } = require('../controllers/CampController')
const { isAuthenticatedUser } = require('../helpers/auth')
const campRouter = express.Router()
campRouter.get('/',isAuthenticatedUser,viewCamps)
campRouter.get('/:id',isAuthenticatedUser,viewCamp)
campRouter.post('/addCamp',addCamp)
campRouter.delete('/delete/:id',deleteCamp)
campRouter.put('/update/:id',updateCamp)
module.exports = { campRouter }