const express = require('express')
const {viewDonors,viewDonor,addDonor, deleteDonor,updateDonor,viewSpecificDonors} = require('../controllers/DonorController')
const donorRouter = express.Router()
donorRouter.get('/',viewDonors)
donorRouter.get('/:id',viewDonor)
donorRouter.post('/addDonor',addDonor)
donorRouter.delete('/delete/:id',deleteDonor)
donorRouter.put('/update/:id',updateDonor)
donorRouter.get('/:bloodGroup/city',viewSpecificDonors)
module.exports = {donorRouter}